### ISSUE TITLE
Which layer the preview watermark in desktop

### ISSUE THREAD

**Issue by laomms** [bho3538/NoDesktopWM#2]
![111](https://user-images.githubusercontent.com/23111726/143968474-713cbb9d-933d-429c-830d-7931a67119a6.png)

it likes the same as ZBID_GENUINE_WINDOWS, but not after testing.

**Comment by bho3538** [comment]
'Evaluation Copy' message is print using 'TextOutW' function in explorer. (not layered window)

if you want remove this message, using this program. (https://winaero.com/download-universal-watermark-disabler/)
